# Generated by Django 4.1 on 2022-08-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220812_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
